name: C/C++ CI

on: [push]

jobs:
  build-win:
    name: Build on Windows (x64)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1
    - name: install Node.js packages
      run: |
        npm install
        npm install -g lcpkg @lcui/cli
    - name: setup
      run: |
        lcpkg setup
        npm run generate-makefile
    - name: install dependencies
      run: lcpkg install --arch x64
    - name: build css
      run: npm run build:css
    - name: build bin
      run: lcui build

  build-linux:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install xmake
      uses: xmake-io/github-action-setup-xmake@v1
    - name: install Node.js packages
      run: |
        npm install
        npm install -g @lcui/cli
    - name: setup
      run: |
        sh ./setup.sh
        npm run generate-makefile
    - name: build css
      run: npm run build:css
    - name: xmake
      run: lcui build --tool xmake
    - name: cmake
      run: lcui build --tool cmake
